app = "present-gen"

[build]
  builder    = "paketobuildpacks/builder:base"
  buildpacks = [
    "paketo-buildpacks/apt",     # <-- installs Aptfile packages
    "paketo-buildpacks/python"   # <-- your Python runtime
  ]

[env]
  FLASK_ENV = "production"

[[services]]
  internal_port = 5000
  protocol      = "tcp"
  [[services.ports]]
    port     = 80
    handlers = ["http"]
  [[services.ports]]
    port     = 443
    handlers = ["tls","http"]


  # Optional: tune concurrency
  #[services.concurrency]
  #  type = "connections"
  #  soft_limit = 25
  #  hard_limit = 50
