app = "present-gen"

# Use the Paketo Buildpacks builder for Python
[build]
  builder = "paketobuildpacks/builder:base"

# Runtime environment variables (secrets managed via flyctl secrets)
[env]
  FLASK_ENV = "production"

# Define the HTTP service
[[services]]
  internal_port = 5000
  protocol = "tcp"

  # Expose ports 80 (HTTP) and 443 (HTTPS)
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Optional: tune concurrency
  #[services.concurrency]
  #  type = "connections"
  #  soft_limit = 25
  #  hard_limit = 50
